// Package fairplay defines the FairPlay v3 SAP key exchange surface used by
// the AirPlay client.
//
// The exchange has four messages:
//
//	client                                            server
//	  ── m1 (16-byte fixed header) ────────────────►   ServerComputeM2
//	  ◄───────────────── m2 (142 bytes) ───────────
//	  ClientComputeM3
//	  ── m3 (164 bytes) ───────────────────────────►   ServerVerifyM3
//	  ◄───────────────── m4 (typically empty) ─────
//
// Both sides then call DeriveKey(m3, ekey) with the SAME m3 and ekey to
// compute a shared 16-byte AES key. The ekey is generated by the client
// and shipped in the SETUP body (out of band w.r.t. /fp-setup).
package fairplay

import "errors"

// FixedM1 is the 16-byte FairPlay v3 client hello sent to /fp-setup.
// Every doubletake session starts with exactly these bytes.
var FixedM1 = []byte{
	0x46, 0x50, 0x4c, 0x59, 0x03, 0x01, 0x01, 0x00,
	0x00, 0x00, 0x00, 0x04, 0x02, 0x00, 0x03, 0xbb,
}

// ErrM3Invalid is returned by Server.VerifyM3 when the supplied m3 is
// not consistent with the m2 the server emitted.
var ErrM3Invalid = errors.New("fairplay: m3 verification failed")

// Client implements the sender side of the FairPlay SAP exchange.
type Client interface {
	// M1 returns the 16-byte client hello to POST to /fp-setup. All
	// known implementations return FixedM1, but the hook exists so a
	// future per-session m1 can be plumbed without changing callers.
	M1() []byte

	// ComputeM3 takes the 142-byte m2 returned by the server and
	// produces the 164-byte m3 to POST back. m3 = 12-byte FPLY framing
	// + 132-byte constant payload + 20-byte hash of m2[14:142].
	ComputeM3(m2 []byte) ([]byte, error)

	// Name identifies the implementation in test output.
	Name() string
}

// Server implements the receiver side of the FairPlay SAP exchange.
//
// In production the server is the Apple TV. The Server interface lets
// us drive a fully in-process exchange for unit tests and for an
// eventual doubletake-as-receiver mode.
type Server interface {
	// ComputeM2 takes the 16-byte m1 and produces the 142-byte m2.
	// The m2 has a 14-byte FPLY-framed header followed by a 128-byte
	// challenge payload that the client hashes into m3.
	ComputeM2(m1 []byte) ([]byte, error)

	// VerifyM3 checks that m3 is a valid response to the m2 this
	// server most recently emitted. Returns ErrM3Invalid on mismatch.
	// Implementations may treat this as a no-op (always-accept) when
	// the underlying receiver does not validate the WB-AES hash.
	VerifyM3(m2, m3 []byte) error

	// Name identifies the implementation in test output.
	Name() string
}

// Session is the convenience wrapper that drives a full exchange in memory.
type Session struct {
	Client Client
	Server Server
}

// Run executes m1 → m2 → m3 → verify and returns the m3 that both
// sides agree on. Both ends will derive the same key by passing this
// m3 (together with the client's ekey) into DeriveKey.
func (s *Session) Run() (m1, m2, m3 []byte, err error) {
	m1 = s.Client.M1()
	m2, err = s.Server.ComputeM2(m1)
	if err != nil {
		return nil, nil, nil, err
	}
	m3, err = s.Client.ComputeM3(m2)
	if err != nil {
		return m1, m2, nil, err
	}
	if err = s.Server.VerifyM3(m2, m3); err != nil {
		return m1, m2, m3, err
	}
	return m1, m2, m3, nil
}
