// Package fairplay defines the FairPlay v3 SAP key exchange surface used by
// the AirPlay client.
//
// The exchange has four messages:
//
//	client                                            server
//	  ── m1 (16-byte fixed header) ────────────────►   ComputeM2
//	  ◄───────────────── m2 (142 bytes) ───────────
//	  ClientComputeM3
//	  ── m3 (164 bytes) ───────────────────────────►   VerifyM3
//	  ◄───────────────── m4 (typically empty) ─────
//
// Both sides then call DeriveKey(m3, ekey) with the SAME m3 and ekey to
// compute a shared 16-byte AES key. The ekey is generated by the client
// and shipped in the SETUP body (out of band w.r.t. /fp-setup).
package fairplay

import "errors"

// FixedM1 is the 16-byte FairPlay v3 client hello sent to /fp-setup.
// Every doubletake session starts with exactly these bytes.
var FixedM1 = []byte{
	0x46, 0x50, 0x4c, 0x59, 0x03, 0x01, 0x01, 0x00,
	0x00, 0x00, 0x00, 0x04, 0x02, 0x00, 0x03, 0xbb,
}

// ErrM3Invalid is returned when the supplied m3 is not consistent with
// the m2 the server emitted.
var ErrM3Invalid = errors.New("fairplay: m3 verification failed")
