//go:build !emulate

package fpemu

import (
	"bufio"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"strings"
	"testing"
	"time"
)

// TestCaptureM2 connects to an Apple TV on the local network, sends m1 to /fp-setup,
// and saves the m2 response for offline testing of FPSAPExchange.
//
// Usage:
//
//	APPLE_TV=192.168.1.77 go test -run TestCaptureM2 ./internal/fpemu/ -v -count=1
//
// The captured m2 is saved as a hex-encoded constant in captured_m2_test.go.
func TestCaptureM2(t *testing.T) {
	host := os.Getenv("APPLE_TV")
	if host == "" {
		t.Skip("Set APPLE_TV=<ip> to capture m2 from an Apple TV")
	}
	port := "7000"

	// m1 from fairplay.go
	m1, _ := hex.DecodeString("46504c590301010000000004020003bb")

	conn, err := net.DialTimeout("tcp", net.JoinHostPort(host, port), 10*time.Second)
	if err != nil {
		t.Fatalf("connect to %s:%s: %v", host, port, err)
	}
	defer conn.Close()

	// Send RTSP request
	req := fmt.Sprintf("POST /fp-setup RTSP/1.0\r\n"+
		"CSeq: 1\r\n"+
		"User-Agent: AirPlay/935.7.1\r\n"+
		"Content-Type: application/octet-stream\r\n"+
		"X-Apple-ET: 32\r\n"+
		"Content-Length: %d\r\n"+
		"\r\n", len(m1))
	conn.Write([]byte(req))
	conn.Write(m1)

	// Read RTSP response
	conn.SetReadDeadline(time.Now().Add(10 * time.Second))
	reader := bufio.NewReader(conn)

	// Read status line
	statusLine, err := reader.ReadString('\n')
	if err != nil {
		t.Fatalf("read status line: %v", err)
	}
	t.Logf("Status: %s", strings.TrimSpace(statusLine))

	// Read headers
	contentLength := 0
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			t.Fatalf("read header: %v", err)
		}
		line = strings.TrimSpace(line)
		if line == "" {
			break
		}
		t.Logf("Header: %s", line)
		if strings.HasPrefix(strings.ToLower(line), "content-length:") {
			fmt.Sscanf(strings.TrimSpace(line[15:]), "%d", &contentLength)
		}
	}

	if contentLength == 0 {
		t.Fatal("no Content-Length in response")
	}

	// Read body
	m2 := make([]byte, contentLength)
	n, err := reader.Read(m2)
	if err != nil || n < contentLength {
		// Try reading more
		for n < contentLength {
			nn, err := reader.Read(m2[n:])
			if err != nil {
				t.Fatalf("read body: got %d/%d bytes: %v", n, contentLength, err)
			}
			n += nn
		}
	}
	m2 = m2[:n]

	t.Logf("m2 (%d bytes): %s", len(m2), hex.EncodeToString(m2))

	// Save as Go source
	goSrc := fmt.Sprintf(`//go:build !emulate

package fpemu

import "encoding/hex"

// capturedM2 is a real m2 response captured from an Apple TV.
// Generated by TestCaptureM2.
var capturedM2 = mustDecodeHex("%s")

func mustDecodeHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}
`, hex.EncodeToString(m2))

	outPath := "captured_m2_test.go"
	if err := os.WriteFile(outPath, []byte(goSrc), 0644); err != nil {
		t.Fatalf("write %s: %v", outPath, err)
	}
	t.Logf("Saved to %s", outPath)
}
