//go:build !emulate

package airplay

import (
	"context"
	"encoding/hex"
	"fmt"
	"os"
	"testing"
	"time"
)

// TestCaptureM2 connects to an Apple TV using saved credentials, authenticates
// via pair-verify, and captures a real m2 response from /fp-setup.
//
// Usage:
//
//	APPLE_TV=192.168.1.77 go test -run TestCaptureM2 ./internal/airplay/ -v -count=1
func TestCaptureM2(t *testing.T) {
	host := os.Getenv("APPLE_TV")
	if host == "" {
		t.Skip("Set APPLE_TV=<ip> to capture m2 from an Apple TV")
	}

	DebugMode = true
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Load saved credentials
	credStore, err := NewCredentialStore(DefaultCredentialsPath())
	if err != nil {
		t.Fatalf("load credentials: %v", err)
	}

	client := NewAirPlayClient(host, 7000)
	if err := client.Connect(ctx); err != nil {
		t.Fatalf("connect: %v", err)
	}
	defer client.Close()

	info, err := client.GetInfo()
	if err != nil {
		t.Fatalf("get info: %v", err)
	}
	t.Logf("Device: %s (%s), ID: %s", info.Name, info.Model, info.DeviceID)

	savedCreds := credStore.Lookup(info.DeviceID)
	if savedCreds == nil {
		t.Fatal("no saved credentials for this device. Run doubletake with --pair first")
	}

	// Set up pair keys from saved credentials
	pub, priv := savedCreds.Ed25519Keys()
	client.PairingID = savedCreds.PairingID
	client.PairKeys = &PairKeys{
		Ed25519Public:  pub,
		Ed25519Private: priv,
	}

	// Pair-verify (uses raw/non-HAP to keep connection plaintext)
	if err := client.PairVerify(ctx); err != nil {
		t.Fatalf("pair-verify: %v", err)
	}
	t.Log("pair-verify succeeded")

	// Send m1, capture m2
	m1 := mustDecodeHexFP("46504c590301010000000004020003bb")
	t.Logf("Sending m1 (%d bytes)", len(m1))

	m2, err := client.httpRequest("POST", "/fp-setup", "application/octet-stream", m1,
		map[string]string{"X-Apple-ET": "32"})
	if err != nil {
		t.Fatalf("fp-setup: %v", err)
	}

	t.Logf("m2 (%d bytes): %s", len(m2), hex.EncodeToString(m2))

	// Save as Go file in fpemu package
	goSrc := fmt.Sprintf(`//go:build !emulate

package fpemu

import "encoding/hex"

// capturedM2 is a real m2 response captured from an Apple TV.
// Generated by TestCaptureM2 in internal/airplay/.
var capturedM2 = mustDecodeHexM2("%s")

func mustDecodeHexM2(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}
`, hex.EncodeToString(m2))

	outPath := "../fpemu/captured_m2_test.go"
	if err := os.WriteFile(outPath, []byte(goSrc), 0644); err != nil {
		t.Fatalf("write %s: %v", outPath, err)
	}
	t.Logf("Saved captured m2 to %s", outPath)
}
